### ISSUE TITLE
[CS] Entity Component System

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#11]
A little further down the line at the moment, but still worth putting on the roadmap.

A component system for implementing quick and re-usable behaviors! C# should do a much better job of this than C, so I think it's an excellent place to start moving over into the C# world. This would probably look a lot like what Unity has in many ways.

I'd love to have components stored in large arrays of structs for cache locality.

**Comment by DirkSonguer** [comment]
When talking about ECS, I found it important to really define what people mean. Are we talking about [this](https://en.wikipedia.org/wiki/Entity_component_system) as defined [here](http://t-machine.org/index.php/2007/09/03/entity-systems-are-the-future-of-mmog-development-part-1/)? If that's the case then we are leaving OOP-style development for a data driven approach (personal opinion: 👍).

Others define it more of a OOP-style super-class / singleton type of approach (personal opinion: 👎). 

When you say "array of structs", then I assume you mean a dynamic array that can contain a number of components an entity currently has and that this can change during runtime?

And while we are at it - there are some tried and proven ECS for CPP and C# out there, why not use one of them? (Although I can see the charm of writing yet another one).
