### ISSUE TITLE
Support special characters

### ISSUE THREAD

**Issue by TopperDEL** [maluoi/StereoKit#116]
I'm using StereoKit with the german language where we have such crazy character like ä, ö, ü, ß - and they don't get rendered on UI-elements like Label.

Could you add support for UTF-8 (or whatever needs to be done to support those characters)? Thank you!

**Comment by maluoi** [comment]
I'll take a peek at this shortly! I do have a lot of work to do for non-latin characters, but I suspect this particular case should be pretty simple.

**Comment by maluoi** [comment]
I add this just now, how's that look to you?

![GermanText](https://user-images.githubusercontent.com/8484884/107701237-7da2fa00-6c6d-11eb-8cc8-e2f3ad185605.jpg)

I have a little bit of cleaning up I need to do, but I can probably put up a new preview build on NuGet later today :)

**Comment by TopperDEL** [comment]
Where did you finde that sample-text? 😂 Yeah, but that looks good. Thank you!
