### ISSUE TITLE
Button with same content get the same animation on press

### ISSUE THREAD

**Issue by TopperDEL** [maluoi/StereoKit#119]
Imagine a Menu with multiple lines and every line ends with a Button containing "Ok". If I click one Ok-Button, all other Buttons with the same text also generate a click-sound and "light up" as they have been pressed.

From my understanding you are copying the object if the text is the same (I assume for performance-optimizations). But in this case I would need the possibility to at least give them different IDs so triggering one button would not "visually" trigger the others.

**Comment by maluoi** [comment]
Yeah, this is a problem with Immediate Mode UIs. I use a hash of the UI element's name to track interactions with those elements. I know Dear IMGUI has a special character postfix that lets them solve this, and I've been considering adding something similar!

However, I do use a hash hierarchy! So it's pretty easily solvable by push/popping a new root id to differentiate them like this:
```CSharp
UI.PushId("1");
UI.Button("Ok");
UI.PopId();

UI.PushId("2");
UI.Button("Ok");
UI.PopId();
```

WindowBegin/End also push/pop a root hash onto the stack, so names in different windows don't collide.

**Comment by TopperDEL** [comment]
It is working with PushId(), so this can be closed.

**Comment by Chris-Tophski** [comment]
@maluoi I hope you excuse me coming back to a closed topic, but I have a follow-up question on the hash hierarchy: You say ``WindowBegin()`` uses this, too; What if I just want a window ID that differs from the window title, so I can have multiple windows with the same title without confusing the engine? Do I have to call ``UI.PopId()`` before or after ``WindowEnd()``?

**Comment by maluoi** [comment]
The same sort of thing applies to windows as well! :)

```csharp
UI.PushId(uniqueId);
{
    UI.WindowBegin(windowTitle, ...);
    {
        UI.Button(buttonName);
    }
    UI.WindowEnd()
}
UI.PopId();
```

Brackets here are optional and just for clarity in indicating hierarchy, but are also valid syntax. In this example, you could basically think of the `Button`'s full id on the hierarchy here as `"uniqueId/windowTitle/buttonName"`!

Hope that helps!

**Comment by Chris-Tophski** [comment]
@maluoi This helps, indeed. Thanks a lot :)
