### ISSUE TITLE
[CS] Scene Graph / Prefab System

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#13]
Something for managing a scene, swapping out scenes, and loading scenes from files! This could probably be mixed with some kind of prefab system, since a prefab is really just a small scene. Bonus points for something that already has an editor?

This could be a core item for a UI framework later on as well, especially if it pulls double duty as a prefab system?

If this is also a prefab, then having a system for promoting child parameters to the root interface would be essential. For example, if there was a complex prefab hierarchy with models, text, icons, etc. like a button, the text field should be promoted to the root so it's easily visible and changeable without having knowledge of the button's prefab hierarchy.

**Comment by adrianimajion** [comment]
I wound up in a Godot discussion thread today where an advantage of that engine was raised I think would be worth thinking about, the Godot scene tree hierarchy can contain additional scenes, which seems like a useful concept not yet supported in unity, for example.  https://docs.godotengine.org/en/3.1/classes/class_scenetree.html
