### ISSUE TITLE
Unable to load dll "SteroKitC" error

### ISSUE THREAD

**Issue by TheEmeraldFalcon** [maluoi/StereoKit#133]
I'm using a new project, I installed both the stable and newest pre-release version of Stereokit via .NET CLI, and get this issue no matter what, at the location of SK.Initialize(new SKSettings{});

This is the full error listing:
```
Exception has occurred: CLR/System.DllNotFoundException
An unhandled exception of type 'System.DllNotFoundException' occurred in StereoKit.dll: 'Unable to load DLL 'StereoKitC' or one of its dependencies: The specified module could not be found. (0x8007007E)'
   at StereoKit.NativeAPI.sk_init(SKSettings settings)
   at StereoKit.SK.InitializeCall(SKSettings settings)
   at StereoKit.SK.Initialize(SKSettings settings)
```

**Comment by maluoi** [comment]
Heyas! Could you let me know:
Operating system
Debug/Release
x64/ARM64
MR/Flatscreen, and which headset?

**Comment by TheEmeraldFalcon** [comment]
Of course!:
Windows 10
Debug (maybe Release I'll check ASAP)
x64
Flatscreen, Oculus Rift S

**Comment by maluoi** [comment]
Ok, thanks, I can get an error that looks like this when using .NET 5.0! Looks like all of my testing has been on 2.0 and 2.1 so far, oops 😨 Looks like it behaves fine on everything below that, so I guess that's the temporary fix!

I'll add that to my test cases, and make sure future updates work with .Net 5.0, thanks for pointing it out!

**Comment by TheEmeraldFalcon** [comment]
Thank you!

**Comment by maluoi** [comment]
Got this all working today, and this'll make it into the next update :)
