### ISSUE TITLE
Color banding on Oculus

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#138]
Easily visible in the Spherical Harmonics generator demo! This may be related to not using 10 bit color yet, or possibly the Rec.2020 color profile that Oculus uses.

**Comment by ClonedPuppy** [comment]
These two links could perhaps be of use:
https://developer.oculus.com/documentation/native/android/mobile-colorspace/  (To set the Android color space)
https://developer.oculus.com/documentation/native/pc/dg-colorspace/  (To set desktop HMD color space)

**Comment by maluoi** [comment]
Alright, I think I finally found a solution to the color space issue! :) Oculus doesn't appear to be implementing the spec properly for `xrEnumerateSwapchainFormats`. It sorts the swapchain formats numerically instead of by platform preference, and so it appeared to be preferring a linear format, which it then proceeds to not convert properly when displaying.

There may also be something I'm generally just missing, since I can't get it to properly display any of the linear formats Oculus claims to support without banding. While formats like `tex_format_rg11b10` look better, there's still obvious banding occurring.

**Comment by maluoi** [comment]
Recent improvements fixed this sufficiently to close the ticket :)
