### ISSUE TITLE
Arm64 Linux binaries in NuGet

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#141]
Linux support is currently x64 only, but there may be some interest in arm64 linux as well. This should be relatively straightforward to add, just needs some messing with build files :)

See this discussion:
https://twitter.com/shlykur/status/1382201356228780032

**Comment by maluoi** [comment]
Lets tack UWP ARM onto this.
https://github.com/maluoi/StereoKit/discussions/180

**Comment by TheBricktop** [comment]
Im very much interested in it.

**Comment by maluoi** [comment]
Thanks for bumping this! I'll take a peek at it again :)

**Comment by maluoi** [comment]
@TheBricktop I now have ARM64 Linux binaries in the v0.3.5-preview.4 build! I haven't tested these though, as I don't have any such device. If you try this out, I would _love_ to know if it works for you or not!

**Comment by TheBricktop** [comment]
I'll try it then
and tell if its working alright
