### ISSUE TITLE
[Docs-Material.SetColor] (Duplicate Instructions)

### ISSUE THREAD

**Issue by JustinM7** [maluoi/StereoKit#153]
Duplicate Instructions listed.

**Comment by JustinM7** [comment]
Misread this.

**Comment by maluoi** [comment]
Haha, you got to it just as I was looking at this! Color vs. Color32, I almost didn't notice the difference either!

**Comment by JustinM7** [comment]
I don't want to get spam-my for every typo so I'll just collect a a few before I file a bug.
