### ISSUE TITLE
Chaining initialization calls Fail

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#16]
Currently chaining the Initialization() calls fails (for example calling it once with Runtime.MixedReality and if that fails with Runtime.Flatscreen) because of some internal configuration that already happened. Ideally this should work.

As per @DirkSonguer's observation.

**Comment by DirkSonguer** [comment]
To elaborate on this, here is the code I would like to work: Trying to open a StereoKit instance with MixedReality and if that fails try to open a flatscreen one.

```csharp
        StereoKitApp kit = new StereoKitApp();
        if (!kit.Initialize("StereoKit C#", Runtime.MixedReality))
        {
            Console.WriteLine("Can't create xr_session!");
            if (!kit.Initialize("StereoKit C#", Runtime.Flatscreen))
            {
                Console.WriteLine("Can't create Desktop window!");
                Environment.Exit(1);
            }
        }
```

**Result**: The desktop window does indeed open, but after a couple of seconds throws a fatal exception, which halts the app. Without investigating I would think that there are some things happening in the MR init routing that are not cleaned up.

Expectation: This sort of chaining / fallback behavior should work or at least a safe way to do it if the developer wants to.

**Comment by maluoi** [comment]
I re-wrote a bunch of initialization stuff to fix a weird issue ( see https://github.com/maluoi/StereoKit/commit/be7205c8c624e5cc6243e8ad062f27872fb29e3a ), and while I was at it, I moved fallback logic to be in StereoKitApp.Initialize itself :)

You can still manually do fallback if you want to (there's a flag!) and the successful runtime is stored in StereoKitApp.ActiveRuntime
