### ISSUE TITLE
Research mode with StereoKit

### ISSUE THREAD

**Issue by cwule** [maluoi/StereoKit#166]
Hi Nick,
The Stereokit is great, love the quick builds!
One suggestion, an example how to integrate research mode, eg. visualization of the different streams with Stereokit or even some processing on the streams would be very useful.

**Comment by maluoi** [comment]
Yeah, that is indeed a pretty good idea! I haven't used research mode myself, so it hasn't gotten too much attention from me yet.

So some questions then!
- Are you interested in using research mode from C#, or C++?
- For stream processing examples, do you mean with something like OpenCV?
- Do you have, or know of any relevant examples that might help accelerate work on this?

**Comment by cwule** [comment]
> Are you interested in using research mode with StereoKit from C#, or C++?

C# would be best, since most of the HL2 development is currently done with Unity, making the adoption of Stereokit easier.

> Do you have, or know of any relevant examples that might help accelerate work on this?

One basic example from the [Hololens2ForCV repo](https://github.com/microsoft/HoloLens2ForCV) would eg. be the visualization of the different streams.

> For stream processing examples, do you mean with something like OpenCV?

Hmm, while this would be great, that would come with a lot of overhead, which you probably want to avoid for Stereokit. Something more basic like reading out a depth value of a pixel in the RGB stream would already be helpful.

**Comment by maluoi** [comment]
Awesome, thanks so much for the details :)

I'm not going to be able to get to this right away, as I expect it's probably not the most trivial of samples. Unfortunately I've got too little time and too many features! :) I may try looking into this after the v0.3.2 release in a few weeks.

**Comment by cwule** [comment]
Thanks for your quick replies, haha, no worries, I know this problem. Looking forward to the next release(s).

**Comment by bo-wu** [comment]
Quite interesting. I am new to Hololens2 and Stereokit, so my question is can I use research mode with Stereokit now?

If I can,  I would like to try  Hololens2ForCV example on Stereokit, since Hololens2ForCV itself  is built on the depreated winrt.

**Comment by AThilenius** [comment]
This might be a very silly question 😬 I see Research Mode marked as "Done" on the Project page for 1.0 but can't find any docs or reference to it's use / existence. I'm after IMU data.
