### ISSUE TITLE
Locatable camera, mediaframe

### ISSUE THREAD

**Issue by cwule** [maluoi/StereoKit#168]
When I use `MediaFrameSourceGroup `to grab camera frames (together with their `SpatialCoordinateSystem`), how would I be able to use these frames in a Stereokit application? I looked at the QR code example where you get a pose for a `SpatialNodeGuid`, I am not clear though how this would apply for getting the pose of eg. the [locatable camera](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/platform-capabilities-and-apis/locatable-camera) with respect to the the world space (like the Unity  `CameraToWorldMatrix `). 

Eg. I would like to
- Grab mediaframe
- extract mediaframe spatialcoordinatesystem
- get world coordinate system
- calculate the CameraToWorldMatrix 

I saw on your twitter that you planned to show an example, is that already possible with the current version of Stereokit together with the MediaFrame reference class?

**Comment by maluoi** [comment]
I vaguely remember writing a snippet that grabbed from UWP's camera API at one point, but I didn't quite get to the spatial alignment part of that code! However, I do expect that there should be enough in place for this to work :)

I believe the relevant method that you'll need here on the StereoKit side is `World.FromPerceptionAnchor`, and you can see an example of this method over [here](https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/Tools/OcclusionMesh.cs#L150). The OpenXR spec this method maps to is [over here](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_MSFT_perception_anchor_interop) as well, if that's of any help! I'm not all that great with this side of the UWP APIs though, I've never figured out quite what's going on with the coordinate system stuff, so I _hope_ that's all you'll need.

**Comment by maluoi** [comment]
I just looked a little deeper into making a sample for this, and I now remember why I hadn't gotten around to it! It looks like it'll take _quite a lot_ of time to figure out and do right! If you get this working and can share some reference code, I'd _love_ to turn it into a StereoKit demo for future reference.

So for now, I'll leave you with my previous snippet. It definitely doesn't do the locating side of things, and could be a lot more efficient! But it does get camera content into a Material, and may serve as useful reference for a thing or two.

```CSharp
static Tex img;
static Material mat;

static MediaCapture mc;
static async void InitMediaCapture()
{
    mc = new MediaCapture();
    await mc.InitializeAsync();

    using (var stream = new InMemoryRandomAccessStream()) { 
        await mc.CapturePhotoToStreamAsync( ImageEncodingProperties.CreateJpeg(), stream);
        DataReader reader = new DataReader(stream.GetInputStreamAt(0));
        byte[] bytes = new byte[stream.Size];
        await reader.LoadAsync((uint)stream.Size);
        reader.ReadBytes(bytes);

        SK.ExecuteOnMain(() => { 
            img = Tex.FromMemory(bytes);
            mat[MatParamName.DiffuseTex] = img;
        });
    }
}
```

**Comment by cwule** [comment]
Thanks a lot for your super quick replies and the code example to get the mediacapture texture! I am also not sure yet how to get the location information as well but will look into it.

**Comment by cwule** [comment]
I am getting the camera frames via [MediaFrameReference](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.frames.mediaframereference?view=winrt-20348), which then delivers me a `SoftwareBitmap`. However, if I convert the `SoftwareBitmap` to a byte array via 

```
SoftwareBitmap softwareBitmap = theSoftwareBitmapIGotFromMediaFrameReference;
WriteableBitmap newBitmap = new WriteableBitmap(softwareBitmap.PixelWidth, softwareBitmap.PixelHeight);
softwareBitmap.CopyToBuffer(newBitmap.PixelBuffer);
bytes = newBitmap.PixelBuffer.ToArray();
img = Tex.FromMemory(bytes);
```
the img stays `null` even though the byte array is full. Any idea why that happens?

**Comment by cwule** [comment]
Oh, got the error here, the Writeable bitmap in this case threw an error. Tried an alternative where I copy the raw image data into buffer via `softwareBitmap.CopyToBuffer(byteArray.AsBuffer());` but I just read in your docs that the Tex.FromMemory does not take a raw color array.
Any alternatives for that?

**Comment by cwule** [comment]
Ok, got it, needed to encode the softwareBitmap bytes. This worked:

```
private async Task<byte[]> EncodedBytes(SoftwareBitmap soft, Guid encoderId)
        {
            byte[] array = null;

            // First: Use an encoder to copy from SoftwareBitmap to an in-mem stream (FlushAsync)
            // Next:  Use ReadAsync on the in-mem stream to get byte[] array

            using (var ms = new InMemoryRandomAccessStream())
            {
                BitmapEncoder encoder = await BitmapEncoder.CreateAsync(encoderId, ms);
                encoder.SetSoftwareBitmap(soft);

                try
                {
                    await encoder.FlushAsync();
                }
                catch (Exception ex) { return new byte[0]; }

                array = new byte[ms.Size];
                await ms.ReadAsync(array.AsBuffer(), (uint)ms.Size, InputStreamOptions.None);
            }
            return array;
        }
```

**Comment by maluoi** [comment]
You can actually create a texture via an array of colors with the `Tex.SetColors` method. It's a slightly different creation pattern! And now that you mention it, I should probably add like a `FromColors` method or constructor as well.

This page is the docs for that, and also includes an example of usage :)
https://stereokit.net/Pages/Reference/Tex/SetColors.html

**Comment by cwule** [comment]
Ok, with your tips, getting the locatable camera was actually quite straightforward. You get the CoordinateSystem from the MediaFrameReference and from that the cameraToWorld Matrix4x4 via Windows.Perception.Spatial API. To then eg. show the camera frame on a plane in front of the user in Stereokit, use:

```
 Vec3 position = cameraToWorld.Value.Translation;
 Quaternion rotation = Quaternion.CreateFromRotationMatrix(cameraToWorld.Value);
 framePose = new Pose(position +  Input.Head.Forward * 0.5f, rotation);   
```

**Comment by maluoi** [comment]
Perfect! Glad that worked out :D

Some cool things to note here as well, a StereoKit `Matrix` is actually a wrapper around a `Matrix4x4`, and you can implicitly convert between them! And as you've already seen, Perception matrices are in the same coordinate space (Right handed, -Z forward). So doing `Matrix mat = cameraToWorld.Value;` works and is perfectly valid.

The SK `Matrix` then has some cool properties, like the ability to extract a `Pose` directly from it :) Can make it a little easier to do stuff like this! 

Also if you're concerned about positioning accuracy, `Input.Head.Forward` might not be good to mix in here. The camera's forward is a little different from the head, and the timestamps between the two could also be a little different. Using the Matrix's forward would be the best! :)
