### ISSUE TITLE
Slider Request

### ISSUE THREAD

**Issue by ClonedPuppy** [maluoi/StereoKit#171]
Would it be possible to have the HSlider only react to input when the user is doing a pinch movement? I find it difficult to design UI panels with more tightly packed buttons that does not cause a problem for the user as they mistakenly slide their finger over the slider(s) while moving in between other buttons. The HSlider grabs input immediately when finger is close, in contrast to the buttons which are more "friendly" as they do allow for some push & give before being activated.

**Comment by maluoi** [comment]
Yeah, I'll noodle on this tomorrow! I do think this is a good idea, and I like your point about 'immediate' vs. 'push & give'.

**Comment by maluoi** [comment]
Present now in v0.3.2!
