### ISSUE TITLE
Intersection Ray with Occlusion Mesh

### ISSUE THREAD

**Issue by cwule** [maluoi/StereoKit#172]
I am using the OcclusionMesh described here #91. Now I would like to check the intersection between a ray and that mesh to spawn a model at the intersection location. Since the OcclusionMesh consists of a list of meshes, I didn't see an easy way to check for an intersection. What would be the best way to check such an intersection?

**Comment by maluoi** [comment]
My recommendation would be to use the recent v0.3.2.preview-2 NuGet build! This adds support for scene understanding into StereoKit's core, so the OcclusionMesh class is no longer needed.

The docs for the relevant methods won't be up until I publish v0.3.2 later in the week, but you can see some [relevant sample code over here](https://github.com/maluoi/StereoKit/blob/develop/Examples/StereoKitTest/Demos/DemoWorldMesh.cs)! Look for `World.Raycast`, and `World.RaycastEnabled` :)

**Comment by cwule** [comment]
Awesome, thanks!
