### ISSUE TITLE
Inconsistencies when changing Renderer.CameraRoot?

### ISSUE THREAD

**Issue by chitsaw** [maluoi/StereoKit#184]
Not sure if this is expected behavior. I am trying to apply a fixed transform such as (0.05, 0.1, 0.05) by setting `Renderer.CameraRoot`. While things like eye gaze and head pose appear to be correct relative to one another (I can run the Eyes demo in StereoKitTest and see the line follow my gaze), some things like the hand meshes are rendered incorrectly relative to my actual hands. The hand input controls function correctly through (I can grab menu handles using my actual hands and UI buttons respond to my actual fingers). Also, the WorldMesh demo renders the mesh offset from the real world (a bit hard to tell in the 2nd image below).

What I am ultimately trying to do is shift everything in StereoKit into a single coordinate system provided by a Windows `StationaryFrameOfReference`, using `World.FromPerceptionAnchor` by following [this example](https://gist.github.com/maluoi/0671623b02dbe5a11997eb769e5ea635) to obtain the transform to apply. I was hoping `Renderer.CameraRoot` would be a quick and inexpensive way of achieving that without having to manually convert everything each time. Does this make sense?

![Offset1](https://user-images.githubusercontent.com/32501077/130847694-c8f650ee-6576-4bfa-8a79-72498f82c039.JPG)
![Offset2](https://user-images.githubusercontent.com/32501077/130847705-6c3518d1-f69e-4924-bc45-157084f2e344.JPG)

**Comment by maluoi** [comment]
Just FYI, I believe these two fixes should resolve your current problem! I'll keep thinking about a feature for setting up a new coordinate system as well, but one way to do that in the meantime would be to use the Hierarchy class :)

**Comment by maluoi** [comment]
FYI, these changes are now present in v0.3.3-preview.4 on NuGet :)
