### ISSUE TITLE
World.FromPerceptionAnchor returns invalid Pose if called before SK.Step()

### ISSUE THREAD

**Issue by chitsaw** [maluoi/StereoKit#188]
In trying to get the `Pose` from a `SpatialAnchor` created shortly after startup, I ran into an interesting issue.

If I call `World.FromPerceptionAnchor()` either before or during the first call to `SK.Step()`, the `Pose` returned appears to be uninitialized, containing invalid values such as [-1.073742E+08]. The following trace error suggests `openxr_get_space` isn't able to locate the anchor's space due to `xr_time` being 0:
```
ERROR (OpenXR) : XrTime must be greater than 0
```
How can I ensure that `xr_time` is not zero before calling `World.FromPerceptionAnchor()`, other than making a dummy call to `SK.Step()` just before, which seems a little bit of a hack. I also tried calling it from _within_ `SK.Step(...)`'s `onStep`, but `xr_time` was still 0 at this point.

In any case, `World.FromPerceptionAnchor()` should probably throw or otherwise indicate failure, rather than silently return an invalid `Pose`.

**Comment by maluoi** [comment]
SK.Step() is probably the best way to achieve this for now, I'll see if I can find a way to set the time during initialization.

xr_time is currently only assigned to when preparing to render, as this is the only spot I knew of that provides the current time. And now that you've mentioned it, there should definitely be a way to get the OpenXR time without waiting until that event! I just have to find it now :)

Also +1 for the failure indication, good call.

**Comment by maluoi** [comment]
FYI, these changes are now present in v0.3.3-preview.4 on NuGet :)

**Comment by chitsaw** [comment]
Tested with v0.3.3-preview.4 and these new changes work nicely! I did run into a different issue related to API deprecation but will open a new issue for that. Thanks so much!
