### ISSUE TITLE
Deprecation of Model APIs causing refcount errors

### ISSUE THREAD

**Issue by chitsaw** [maluoi/StereoKit#190]
After replacing some of the recently deprecated methods on the `Model` class, I started seeing crashes in my app and noticed the following trace output:

`[SK error] Released too many references to asset!`

The methods replaced were:

```
model.AddSubset() -> model.AddNode()
model.GetMesh(0) -> model.Visuals[0].Mesh
model.SetMaterial(0, material) -> model.Visuals[0].Material = material
```

Seems like the new pattern creates a `ModelNode` object which has a finalizer that calls `model_release` on the underlying model instance, but there does not appear to be any corresponding call to `model_addref`?

**Comment by maluoi** [comment]
Yeah, does look like it! Thanks for catching that, I'm a little surprised I didn't see that one already. I'll have to find a way to trip those finalizers reliably during testing.

This should be an easy fix, I'll hunt that all down and make sure those references are right :)

**Comment by maluoi** [comment]
Alright, pretty sure I got it! I was able to repro it with calls to GC.Collect, and the fix I put in solves those. If it's still popping up anywhere, let me know! I just pushed v0.3.3-preview.5 to NuGet with these changes :)

**Comment by chitsaw** [comment]
Yup, all seems to be working good now. Thanks for the quick fix (and updated NuGet as well)!
