### ISSUE TITLE
Projecting virtual objects onto camera frame / MediaFrame Coordinate System

### ISSUE THREAD

**Issue by austinbhale** [maluoi/StereoKit#196]
Hi Nick 👋 Thanks for this incredible library!

#### Background
I am writing a UWP application for the HoloLens 2 to grab the exact pixel coordinates of a StereoKit virtual object in an image. Below, I've written an excerpt of the code that attempts to communicate between MediaFrame's and StereoKit's coordinate systems using a spatial anchor.

The issue I'm running into is that there is a consistent offset in an image (in y), no matter the depth of an object from the camera origin.

For example, the world (z-forward) & pixel coordinates (x-right, y-down) are printed for each cube. The red dots represent the projected values, while the green dots are each 45 pixels above the red dots:

![20211004_181709_HoloLens](https://user-images.githubusercontent.com/32556981/135946482-8004e783-e938-417d-ad0c-cbf3c285996d.jpg)
(1280x720 image)

#### Two assumptions
1. I'm assuming that the camera's origin from the spatial anchor is the center of the camera frame in StereoKit's coordinate system. Would the ability to change the world origin to MediaFrame's be useful in this case, as referenced in #189 & #184?
2. Microsoft's [ProjectOntoFrame](https://docs.microsoft.com/en-us/uwp/api/windows.media.devices.core.cameraintrinsics.projectontoframe?view=winrt-20348) method accounts for the principal point offset in an image, since a similar algorithm results in the same pixel coordinate value:

![image](https://user-images.githubusercontent.com/32556981/135943974-d7da9714-9b08-46ce-9c5e-bf11e03d757a.png)
which is equivalent to the following code:
```
Vector2 l = new Vector2(
    _cameraIntrinsics.FocalLength.X * projCubePose.position.x / projCubePose.position.z + _cameraIntrinsics.PrincipalPoint.X,
    _cameraIntrinsics.FocalLength.Y * projCubePose.position.y / projCubePose.position.z + _cameraIntrinsics.PrincipalPoint.Y
);
Point pixelCoordinate = new Point(l.X, _cameraIntrinsics.ImageHeight - l.Y);
```

#### Code excerpt
```
// class members
private SpatialCoordinateSystem _worldCoordinateSystem;
...
// inside our class, once our media frame arrives
VideoMediaFrame videoMediaFrame = mediaFrameReference?.VideoMediaFrame;
TimeSpan? timeSpan = mediaFrameReference.SystemRelativeTime;

if (timeSpan.HasValue)
{
    PerceptionTimestamp perceptionTimestamp = PerceptionTimestampHelper.FromSystemRelativeTargetTime(timeSpan.Value);

    // Stationary coordinate system has similar results, since it establishes itself once in the beginning?
    // The alternative would be:
    // spatialLocation = SpatialLocator.GetDefault().TryLocateAtTimestamp(perceptionTimestamp, _worldCoordinateSystem);

    _worldCoordinateSystem = _referenceFrame.GetStationaryCoordinateSystemAtTimestamp(perceptionTimestamp);
}

var camera2World = mediaFrameReference.CoordinateSystem.TryGetTransformTo(_worldCoordinateSystem);
if (camera2World.HasValue)
{
    Matrix camera2WorldSK = camera2World.Value;
    CameraIntrinsics cameraIntrinsics = videoMediaFrame.CameraIntrinsics;
    SpatialAnchor anchor = SpatialAnchor.TryCreateRelativeTo(_worldCoordinateSystem, camera2WorldSK.Translation, camera2WorldSK.Rotation);
    Pose camOrigin = World.FromPerceptionAnchor(anchor);
    
    Matrix leftToRight = new Matrix(
        1, 0,  0, 0,
        0, 1,  0, 0,
        0, 0, -1, 0,
        0, 0,  0, 1
    );
    
    // label is a pose of some drawn cube in the scene
    Pose toLabel = camOrigin.ToMatrix().Inverse.Transform(label);
    
    // Convert to Right-Hand Coordinate System (+z forward)
    Pose projCubePose = leftToRight.Transform(toLabel);
    
    // Check our pixel coordinate
    Point pixelCoordinate = _cameraIntrinsics.ProjectOntoFrame(projCubePose.position);
}
```

This is a rather long post, but I hope this issue is relevant for others too. Any advice would be highly appreciated!

**Comment by maluoi** [comment]
Hey thanks for the kind words!

I haven't dug into this code too deeply yet, but I believe @cwule got something very similar to this working not so long ago! The discussion started over at #168, and in a separate communication I also pointed to [this code](https://github.com/maluoi/StereoKit/blob/develop/Examples/StereoKitTest/Demos/DemoWorldAnchor.cs#L26) that's decent reference for `World.PerceptionAnchor`.

I don't think I'd use anything like `Renderer.CameraRoot` in a case like this, that's probably a bit much! `World.FromPerceptionAnchor` is definitely the best and most appropriate way to go about the coordinate space conversions.

Let me know if any of that jogs something loose for you! If not, I'll try and dig in more later. And if @cwule drops in here as well, it's possible he might be able to spot what's missing a little easier than I.

**Comment by cwule** [comment]
In [this previous example](https://imgur.com/a/jRwzJRM), switching from `SpatialLocator.GetDefault().CreateStationaryFrameOfReferenceAtCurrentLocation().CoordinateSystem` (bottom image) to `World.FromPerceptionAnchor` (top image) lead to a much better alignment of camera frame to the real world. Since you are alredy using `World.FromPerceptionAnchor` in your code, that unfortunately won't help you much. And as you can see in my images, I also still have a small offset of 2-3cm between the camera frame and the real world, which is a similar offset as you observe. Would be great to understand what the reason for this offset is. It seems suspiciously close to the y-offset of the RGB camera to the eyes, however I suppose that this should have already been accounted for with the `World.FromPerceptionAnchor`.

**Comment by austinbhale** [comment]
Thanks for your help @maluoi @cwule! The spatial anchor worked perfectly. The cause of error in this case was Microsoft's ProjectOntoFrame calculations. They must be forgetting that +y is down for the pixels, because I get the exact location when I do the following:

Change
```
_cameraIntrinsics.FocalLength.Y * projCubePose.position.y / projCubePose.position.z + _cameraIntrinsics.PrincipalPoint.Y
```
to
```
-(_cameraIntrinsics.FocalLength.Y * projCubePose.position.y / projCubePose.position.z) + _cameraIntrinsics.PrincipalPoint.Y
```

**Comment by maluoi** [comment]
Glad you found it, and thanks a bunch for sharing the details! :)
