### ISSUE TITLE
Feature request: Ability to set object visibility on headset and MRC seperately.

### ISSUE THREAD

**Issue by halilibrahim** [maluoi/StereoKit#206]
I'm trying to make mixed reality capture on Hololens 2 with [MediaCapture API](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture). What I want is to capture holograms on video but not show them on Hololens during capture.
Please add feature to set hologram hidden on headset, but record those hidden objects on mixed reality capture.

**Comment by maluoi** [comment]
This is now available in v0.3.4, enjoy!
