### ISSUE TITLE
[Docs-Guides Drawing] Links not found (404)

### ISSUE THREAD

**Issue by cgassman** [maluoi/StereoKit#215]
Hi, as a complete beginner to stereokit and opensource, I'm reading through all your docs and found the following to issues:

In sections 'Models' and 'Cool!' the link to the **Model guide** results in a 404 - https://stereokit.net/Pages/Guides/Working-with-Models.html 

In section 'Meshes and Materials' the link to the **Material guide** results in a 404 - https://stereokit.net/Pages/Guides/Materials-and-Shaders.html

thanks for preparing all the helpful material, making it easier to make first steps in this area!!!

**Comment by maluoi** [comment]
Thanks for bringing these up! They should be fixed now :)

I hope to get to the Model Guide soon, but in the meantime I've directed that link to some [relevant code](https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/Demos/DemoNodes.cs) from the samples that may eventually be the bones for the Model Guide later on.
