### ISSUE TITLE
Trouble building from source in directory containing spaces

### ISSUE THREAD

**Issue by paulmelis** [maluoi/StereoKit#218]
First, I've worked with Unity and VS to do HL2 development, but am new to StereoKit. I'm also more of a Linux developer ;-) So I'd like to get the demo project working, as I'm assuming it will allow me to test the different demos in the https://github.com/maluoi/StereoKit/tree/master/Examples/StereoKitTest/Demos folder. I'm trying build the top-level StereoKit.sln solution in this repo, having disabled the android and documenter projects. In Debug/ARM64 configuration building fails with these errors:

![image](https://user-images.githubusercontent.com/1408287/141672148-3c21a47f-c6a6-4908-996c-5a0a52d92750.png)

Some of these are probably due to dependencies between the projects in the solution, where at least one of them fails. But I'm having trouble spotting the error(s) and subsequent figuring out how to fix them. This is with VS Community 2019 on Windows 10. Are there step-by-step instructions on how to get the demos to build?

**Comment by slitcch** [comment]
You're a Linux developer, huh? have you heard of https://monado.freedesktop.org ? ;) It's an OpenXR runtime for Linux; works with Valve Index, North Star, and WMR headset support is coming soon. Works great with StereoKit too

**Comment by paulmelis** [comment]
Okay, managed to figure out what's going on: the directory the repo was stored in contained spaces. Some of the build commands are not using quoting of the solutions dir, hence some commands failed to run. Also, I see a checkout of an OpenXR repo as part of the build, followed by a number of calls to cmake. But the latter is not installed (yet), so I'm wondering it that should be listed as a build dependency in the readme. Anyways, I'll update the title of this issue to reflect the actual problem

**Comment by maluoi** [comment]
Thanks for hunting down the details here! It does look like the shader compiler steps in particular here may be tripping on the spaces.

Sounds like I may just need to set up my dev folder with a space in it :)

**Comment by maluoi** [comment]
I've been working on `/develop` with a space in my folder name for about a week, and I'm pretty sure I've gotten all the stragglers! I'll close this now, but it won't be in `/master` until the full release of v0.3.5.
