### ISSUE TITLE
World mesh update rate

### ISSUE THREAD

**Issue by paulmelis** [maluoi/StereoKit#220]
With the World Mesh demo it seems the mesh doesn't reliably update when something in the environment changes (e.g. chair moved). At least, I haven't seen it update while the mesh in being shown. After hiding it and doing some ray casting it does seem to update, but I can't detect when or why. I had a Unity-based app that also showed the world mesh, but there updating happened fairly quickly (a few seconds at most). Is there something specific in StereoKit that blocks updates?

**Comment by maluoi** [comment]
StereoKit's occlusion mesh is powered by the Scene Understanding extension, which is a bit of a different system from most occlusion stuff! Occlusion specific APIs are generally designed for fast content refreshing, but SU doesn't quite work that way. However, it can totally refresh faster that what it's doing right now and I'm probably overdue to add some configuration options to it. Right now, it's set up to only update the mesh when you walk outside of a certain radius.

I'll take a look at this and see if can expose some decent options for configuring the refresh rate in the next preview build.

**Comment by maluoi** [comment]
These changes are live in v0.3.5-preview.2! See: `World.RefreshType`, `World.RefreshRadius`, and `World.RefreshInterval`. These aren't available on the docs site until v0.3.5 is out completely, but you can see some sample usage [over here](https://github.com/maluoi/StereoKit/blob/develop/Examples/StereoKitTest/Demos/DemoWorldMesh.cs#L22).

I'll close this issue, but feel free to open another one or bump this one if you run into trouble with it!
