### ISSUE TITLE
Couldn't able to install StereoKit templates

### ISSUE THREAD

**Issue by ayushtamra** [maluoi/StereoKit#221]
Hello!
I just started with StereoKit, Through Guides and the on demand videos I installed visual code and added .NET desktop development and UWP payloads, then I downloaded the StereoKit templates from the marketplace but got an error stating
`This extension is not installable on any currently installed products`
I think its due to the fact that I installed visual studio 2022.
So will my apps work fine if I do it through the Nuget package?

**Comment by maluoi** [comment]
If you set the project up manually with the NuGet package, it'll work just fine! The VS 2022 release snuck up on me, so yeah, the templates are unfortunately still set up for 2019 :)

**Comment by ayushtamra** [comment]
Okay got it,
Thanks @maluoi

**Comment by maluoi** [comment]
I just updated the templates to work with VS 2022! If you try it out, I'd love to hear if they work for you :)

**Comment by maluoi** [comment]
I will close this now, as it's been working well for me so far. If you encounter issues with the 2022 templates later on, please let me know :)

**Comment by ayushtamra** [comment]
Hi @maluoi !
Sorry for replying late, I have installed StereoKit templates and it works pretty fine, I have one question why the .NET core runtime default to 3.1.0

**Comment by maluoi** [comment]
3.1 is the oldest version of .Net Core that's still in support, the templates kinda use it for broader compatibility? It's somewhat arbitrary. StereoKit works perfectly well with newer versions of .Net Core as well, so feel free to update it to a newer version!

**Comment by Abdul-Mukit** [comment]
Hello,
I downloaded the SK templates and created a new project using the UWP template. I tried building it but I can't seem to get rid of the errors. I am using visual studio 2022.

![image](https://user-images.githubusercontent.com/29538019/214473555-debde831-9b5e-4060-a4e4-7c9eaa7efed2.png)
