### ISSUE TITLE
SKMath.AngleDist does not behave as labeled.

### ISSUE THREAD

**Issue by Strepto** [maluoi/StereoKit#232]
## Description

This might be me reading the docs wrong, but I'm adding the issue anyway. 

I would expect the angle distance between the two below to be identical, but the actual results are very different.

```cs
var angleDistA = SKMath.AngleDist(0, 359);
var angleDistB = SKMath.AngleDist(359, 0);

// Will return 
// angleDistA  => 179 <- Wrong?
// angleDistB  => 1 <- Correct
```

## Platform / Environment

StereoKit 0.3.5-preview.2

**Comment by maluoi** [comment]
You're absolutely correct, thanks for the report! This'll be fixed in the next build, and I've added some tests for this.

**Comment by maluoi** [comment]
Preview build v0.3.5-preview.3 is now up and contains this fix, so I'm closing this now! Feel free to re-open this if you still have issues with it!
