### ISSUE TITLE
Quat.LookAt() description

### ISSUE THREAD

**Issue by paulmelis** [maluoi/StereoKit#239]
I'm using `Quat.LookAt()` it to control the rotation of a piece of text somewhere in the scene, so that it always faces the head position. It seems I need `LookAt(text_pos, Input.Head.position - text_pos, Vec3.UnitY)` for this (after quite a bit of trial and error to get it right). 

What makes it confusing is that apparently the description for the 3-argument version (listed first in the docs) is based on the 2-argument version, so things like "the direction of the *two vectors* provided to the function" are ambiguous (there's 3 vectors). And also the "Up is always (0,1,0)" statement is incorrect. 

Also, the meaning of the `from` argument could be interpreted as either the "resting direction" or the object position. I now understand it is a position, and not the "resting direction". Apparently, the latter is always Vec3.Forward?

**Comment by maluoi** [comment]
I dunno what I was thinking when I wrote that, I don't believe that was a terribly good explanation! I've revised the [docs for Quat.LookAt](https://stereokit.net/Pages/Reference/Quat/LookAt.html), and provided a bit of sample, hopefully it's a bit clearer now?

**Comment by paulmelis** [comment]
Thanks for the quick update, this indeed seems a lot clearer. It actually didn't occur to me that the second argument is also a position (though it was a direction vector). 

One question I still have is whether the returned rotation is guaranteed to be purely around the up direction? A simple test with orienting text seems to show rotation in another axis in extreme cases.

**Comment by wimachtendink** [comment]
I might just be misunderstanding, but using the term "normal" even in single quotes is slightly tempting to misinterpret in some planar sense. I might suggest something like "regular", "common", or "standard".

**Comment by maluoi** [comment]
> It actually didn't occur to me that the second argument is also a position (though it was a direction vector).

Yeah, I was incorrectly using the word `direction` there, and it was pretttty confusing! If you do have a direction already though, `Quat.LookDir` is much nicer! :)

> One question I still have is whether the returned rotation is guaranteed to be purely around the up direction? A simple test with orienting text seems to show rotation in another axis in extreme cases.

The up direction in the context of the LookAt function is primarily about Z axis roll, rather than specifying the exact direction for the top! If you think about two points, `from` and `at`, it's just a line that could represent any number of possible rotations when considering Z axis roll. X and Y rotations are locked in nicely enough, but Z is free without specifying an 'up' direction.

> but using the term "normal" even in single quotes is slightly tempting to misinterpret in some planar sense

That's an excellent point, it's quite the overloaded word!

**Comment by maluoi** [comment]
Just made some additional changes to [the doc](https://stereokit.net/Pages/Reference/Quat/LookAt.html), look any better?
