### ISSUE TITLE
UI.Space() on the same line broken

### ISSUE THREAD

**Issue by paulmelis** [maluoi/StereoKit#248]
## Description

I have a number of buttons on the same line in a UI window, and I want to separate one of them to be away from the others:

```
                ... other buttons
                if (UI.Button("Clear")) ...
                UI.SameLine();
                UI.Space(0.02f);
                if (UI.Toggle("Scan", ref scanning)) ...
```

The `UI.Space()` call seems perfect for this and should support horizontal spacing according to the docs. But it appears to shift the button directly after the `UI.Space()` call in the wrong direction. I.e. with the example above The "Clear" and "Scan" buttons end up overlapping and I need to use `UI.Space(-0.02f)` to get the appropriate separation.

## Platform / Environment

Windows UWP, C#, SK 0.3.4

**Comment by maluoi** [comment]
Thanks for this one! I've got a fix for it that'll be in the next preview build!

**Comment by maluoi** [comment]
Preview build v0.3.5-preview.3 is now up and contains this fix, so I'm closing this now! Feel free to re-open this if you still have issues with it!
