### ISSUE TITLE
Some controls over UI element width or horizontal placement

### ISSUE THREAD

**Issue by paulmelis** [maluoi/StereoKit#257]
## Describe the feature

Having the option to set an explicit width for UI elements, such as buttons, would be a nice addition. It's currently not easy to have elements from different lines align with each other (e.g. a grid of button spanning multiple lines). Also, for the case where you render buttons based on dynamic text (e.g. a name set at runtime) it would also be great to be able to limit the button width for very long labels, so buttons don't grow in width too much.

**Comment by maluoi** [comment]
Most UI elements have an overload that takes a `size` parameter! So you can absolutely do something like this already:

`UI.Button("Fixed Width", new Vec2(10*U.cm, 0));`

Note that for functions like this, passing in 0 for an axis size will tell it to auto-size. For X, this is usually the panel's remaining width, and for Y, this is usually the same as `UI.LineHeight`.

There's not really a built-in Min(width, textWidth), but you may be able to pair the size overloads with `Text.Size` function to achieve this manually.

**Comment by paulmelis** [comment]
Argh, why doesn't the documentation show these extra overloads?

**Comment by maluoi** [comment]
Two main reasons!

I still have some concerns about "documentation duplication" that I haven't quite resolved yet. Much like code, duplicated documentation is harder to maintain, and overloads are a big offender here. I haven't set up patterns or systems to handle this well for me yet, so I've occasionally skipped documenting overloads in cases where I'm less confident about the API surface.

Robust UI layout is still a bit of an open problem right now, and I'm unconvinced that a size overload will be sufficient in the long run. It works for now, but I intend to have better tools for designer friendly layout soon. I'm just uncertain what that looks like yet at the API level, so these overloads have an uncertain future.
