### ISSUE TITLE
Empty window type grabbable?

### ISSUE THREAD

**Issue by paulmelis** [maluoi/StereoKit#259]
## Description

The UIWin docs says for the `Empty` value that "none of the window will be grabbable". However, when you use `UI.WindowBegin("Title", ref awin_pose, size, UIWin.Empty);` this results in a window that *can* be grabbed and moved.

## Platform / Environment

HoloLens 2 (C# UWP)

**Comment by maluoi** [comment]
This does seem like I missed some stuff! There's a `UIMove.None` available in the C API, and it looks like I missed adding C# bindings for it! `UIWin.Empty` probably shouldn't have that description either, as `UIMove.None` covers that behavior instead. I'll make sure these get fixed for the next update.

**Comment by maluoi** [comment]
Also, if you're wanting an empty ungrabbable window, it's possible you may just want [`UI.Push/PopSurface`](https://stereokit.net/Pages/Reference/UI/PushSurface.html)! You can pair this with [`UI.Push/PopId`](https://stereokit.net/Pages/Reference/UI/PushId.html) if you also still want the Id encapsulation that the window provides.
