### ISSUE TITLE
About Projection 

### ISSUE THREAD

**Issue by liupucn** [maluoi/StereoKit#264]
![企业微信截图_16395539176609](https://user-images.githubusercontent.com/34471331/146144605-d869be4a-7634-42d5-9860-68f9d709a9a4.png)
![企业微信截图_16395540576964](https://user-images.githubusercontent.com/34471331/146144617-a6c5f0e5-b582-44ad-b5b0-5ecda24031ca.png)
It has a different result when I see in hololens and by live stream.

**Comment by maluoi** [comment]
Which app is this? I'm not familiar with it.

HoloLens 2 has a new feature that I've generally called "3rd eye render", OpenXR calls this a "1st person observer", and the Device Portal calls this "Render from Camera". Basically, it renders the scene a 3rd time from the perspective of the PV camera, which ensures that holograms line up nicely.

If your software here is not enabling that feature, or doesn't know about the feature, then there's a good chance it's just grabbing a view from one of the eyes and overlaying that on the camera stream. This was how HoloLens 1 did it, and it's still a fallback solution for applications that don't support it, or as an option to save on performance by skipping the 3rd render.

**Comment by maluoi** [comment]
I suspect this is just an old app without proper support for "Render from Camera". Without any additional information, I'm just going to close this now :)
