### ISSUE TITLE
ModelNode.Mesh -> Discrepancy between Docs and Implementation

### ISSUE THREAD

**Issue by Strepto** [maluoi/StereoKit#302]
https://github.com/maluoi/StereoKit/blob/9539082a7db2fb5b6577e5517c0c9f99ab499ebc/StereoKit/Assets/Model.cs#L561-L567

The docs say it can return null, but it can neither be `set` to null or `get` null. 

When I try to **set** it to `null` I get a crash. 

When I try to retrieve a non intialized ModelNode.Mesh i get a new Mesh reference, but cannot figure out if is should be a null reference.

Failing test example :)
```cs
Model model = new Model();
var node = model.AddNode(null, Matrix.Identity, mesh: null)
Assert.That(node.Model, Is.Null); 
```

**Comment by maluoi** [comment]
This is now up on NuGet in v0.3.6-preview.3 :)
