### ISSUE TITLE
Why there is no support for HoloLens 1 ?

### ISSUE THREAD

**Issue by AlexPiro** [maluoi/StereoKit#307]
As HL 2 now replaced the HL1 , I still like to work with my HL1 in parallel of HL2.
So I was wondering if it's possible to build for HL1 or if there is incompatibility with this device ? Maybe the OpenXR support ?

**Comment by maluoi** [comment]
StereoKit can't deploy to HoloLens 1, which unfortunately does not support OpenXR! Right now, StereoKit only supports OpenXR compatible devices.

The Microsoft [official docs](https://docs.microsoft.com/en-us/hololens/hololens1-release-notes) do state this:
> HoloLens (1st gen) has entered Long Term Servicing (LTS) state. Future updates will focus on issue and security fixes, while maintaining feature parity with the Windows 10 Holographic, version 1809 release for HoloLens (1st gen).
>
> For developers, this means that HoloLens (1st gen) apps will not support the OpenXR API. These headsets remain supported in Unity 2019 LTS with the WinRT API backend for the full lifecycle of Unity 2019 LTS through mid-2022.
