### ISSUE TITLE
Separate progress bar from HSlider

### ISSUE THREAD

**Issue by ClonedPuppy** [maluoi/StereoKit#326]
There is a alternate use case for the slider that I've been using quite a lot lately, and that is to hook up the ref value to non interactive stuff.  Really useful for stuff like load indicators and other things where you need a visual indication of volume from one value to another. 
Feel free to ignore this little request, because it works fine as it is, however it would be uber slick if we could have a option to just disable the "slide" interactivity completely, so it just behaves completely as a indicator (maybe even with non protruding knob!).

**Comment by maluoi** [comment]
I'll refactor the slider bar out of HSlider, and use that as a separate element!

**Comment by maluoi** [comment]
This is available in v0.3.6-preview.4!
