### ISSUE TITLE
displayPreference = DisplayMode.Flatscreen provides no interaction?

### ISSUE THREAD

**Issue by paulmelis** [maluoi/StereoKit#338]
When developing on .Net desktop and running with `displayPreference = DisplayMode.Flatscreen` I do get the simulator window as expected, but it seems no interaction is possible. Plus I see the waiting indicator (blue rotating circle). The virtual hands do respond to mouse interaction, but nothing else seems to be possible. Any idea what could be causing this? 

Below what little log output there is:

```
[SK diagnostic] Initializing StereoKit v0.3.5...
[SK diagnostic] Initialized Assets
[SK diagnostic] sk_gpu: Using Direct3D 11: NVIDIA GeForce RTX 3090
[SK diagnostic] Starting flatscreen mode
[SK diagnostic] Created swapchain: 1280x720 color:rgba32_linear depth:depth32
[SK diagnostic] Initialized Platform
[SK diagnostic] ISAC audio backend not available, falling back to miniaudio! It's likely the device doesn't have Windows Sonic enabled, which can be found under Settings->Sound->Device Properties->Spatial Sound.
[SK info] Using audio backend: WASAPI
[SK diagnostic] Initialized Audio
[SK diagnostic] Initialized Defaults
[SK diagnostic] Initialized World
[SK diagnostic] Initialized Sprites
[SK diagnostic] Initialized Lines
[SK diagnostic] Initialized UI
[SK diagnostic] Initialized Renderer
[SK diagnostic] Initialized Physics
[SK diagnostic] Initialized Input
[SK info] Initialization successful
[SK info] Fetching model index
[SK info] Waiting for model list
[SK info] Model: IridescentDishWithOlives.glb
[SK info] Model: plane-1m.glb
[SK info] Model: photogrammetry-sand-lime-brick-factory.glb
[SK info] Model: suzanne.glb
[SK info] Have 4 models
```

The regular `OpenXR session begin` seems to be the point at which output stops? Removing the `displayPreference` override makes the application work in an XR-3 headset.

**Comment by maluoi** [comment]
Your log doesn't seem to show any red flags here, this is a successful initialization that has properly advanced into your application code!

> I do get the simulator window as expected, but it seems no interaction is possible.

Could you provide a bit more detail about this? Which interactions are you trying to do, is this like, simulator inputs like WASD and pinch/grasp aren't working, or the UI isn't reacting to hand input?

> Plus I see the waiting indicator (blue rotating circle).

I could imagine something like this if the app got caught in an infinite loop, but I'm not actually sure what would cause this if the simulator is still responsive! Is this in place of the mouse, or hovering over the simulator window?

**Comment by paulmelis** [comment]
> Could you provide a bit more detail about this? Which interactions are you trying to do, is this like, simulator inputs like WASD and pinch/grasp aren't working, or the UI isn't reacting to hand input?

So the only interaction that appears to do anything is moving the mouse, for which the hand model moves. But I can find no keyboard or mouse action that does anything. This is with testing on my normal dev laptop (which doesn't have the Varjo headset connected).

> I could imagine something like this if the app got caught in an infinite loop, but I'm not actually sure what would cause this if the simulator is still responsive! Is this in place of the mouse, or hovering over the simulator window?

Yes, the regular mouse cursor is replaced by the waiting indicator. But I'm trying to understand where that indicator comes from anyway. If I create a new SK .Net Core project and simply run the templated code (Debug, Any CPU mode) then I also see the busy indicator, even though all the interactions *do* seem to work ok. The indicator for some runs goes away after a few seconds, and for some stays around. If I do the same for the UWP template (Debug, x64 mode) the loading indicator stays around for 1-2 seconds, but then disappears and simulator interaction seems to be fine. Would you have any clue where the indicator comes from?

**Comment by paulmelis** [comment]
I'm starting to think the `displayMode` value was a red herring and my code doesn't run well (i.e. no interaction) in the simulator anyway. I have no idea what exactly makes it works when running on true OpenXR on the XR-3, but I suspect it might have something to do with async code. As I'm running a `HttpClient` request at startup, which I `await` somewhere further down the code (but before entering the main render loop) my `Run() and `Main()` methods are marked `async` and have return value `Task`. This whole async programming is a bit new to me (I'm more at home with regular multi-threading), so I might be doing something wrong that is causing the lockup in simulator mode (but no idea why it doesn't also happen then in OpenXR mode). 

On a high level my code is structured like this:

```
class Application
{
    HttpClient http_client;

    async Task Run()
    { 
        http_client = new HttpClient();
        Task<HttpResponseMessage> fetch_models_task = http_client.GetAsync(FileURL("index.txt"));

        // scene initialization stuff

         HttpResponseMessage models_response = await fetch_models_task;
         if (models_response.StatusCode == System.Net.HttpStatusCode.OK) { /* process response */ }
    
         while (SK.Step(() =>
         {
              // Draw models and UI
         }
    }

    static async Task Main(string[] args)
    {            
            SKSettings settings = new SKSettings
            {
                appName = "ModelViewer",
                assetsFolder = "Assets",
            };

            if (!SK.Initialize(settings))
                Environment.Exit(1);

            Application app = new Application();
            await app.Run();

            SK.Shutdown();
     }
}
```

Should this work as expected?

**Comment by maluoi** [comment]
Okay, I do see the same issue as well when running this code! The window is becoming "unresponsive" while the application is still continuing, which is absolutely wild! I'm not an expert at async code either, but this definitely looks a little odd to me :D I've never seen an async Main before, that's for sure!

I trimmed the async code to be a bit less contagious, and this seems to remove the issue. Removing async from `Main` wasn't enough on its own, I also needed to remove async from `Run`. Still not certain what exactly was happening there though! Async code seems to have a tendency to be a little contagious? When it does that, it's often a good idea to stop the contagion using some of the Task methods/properties. I kinda use `Task.Run`, `task.Result` and `task.ContinueWith` a good bit, and usually use `await` to avoid nesting callbacks?

```csharp
using StereoKit;
using System;
using System.Net.Http;

class Application
{
	HttpClient http_client;

	void Run()
	{
		http_client = new HttpClient();
		http_client.GetAsync("https://playdeck.net/").ContinueWith(t=>{
			HttpResponseMessage models_response = t.Result;
			if (models_response.StatusCode == System.Net.HttpStatusCode.OK) { /* process response */ }
		});

		// scene initialization stuff
		while (SK.Step(() =>
		{
			// Draw models and UI
		}));
	}

	static void Main(string[] args)
	{
		SKSettings settings = new SKSettings
		{
			appName = "ModelViewer",
			assetsFolder = "Assets",
		};

		if (!SK.Initialize(settings))
			Environment.Exit(1);

		Application app = new Application();
		app.Run();

		SK.Shutdown();
	}
}
```

**Comment by paulmelis** [comment]
Hmm, that's an interesting way of handling the async stuff. However, within the lambda function you added to process the response I need to do `response.Content.ReadAsStringAsync()` (as I don't see another way to get the string). Which then again leads to having to use `await` on that call, which then contaminates the lambda itself, and the function it's called within, etc. What would be a good way to handle that? Maybe I'm better off using `WebClient.DownloadString()`

**Comment by maluoi** [comment]
You should be able to just say `response.Content.ReadAsStringAsync().Result`? You may also be able to turn the lambda into a named async function of its own, or perhaps there's some way to make an async lambda :D

**Comment by paulmelis** [comment]
> You should be able to just say response.Content.ReadAsStringAsync().Result?

Thanks, that did the trick.

I guess we can close the original issue here, although I'll check next week to see if the lockup is indeed gone now on the system the XR-3 is connected to.

**Comment by maluoi** [comment]
Sounds great! I expect that should do the trick, but yeah, feel free to pop this one back open if something persists :)
