### ISSUE TITLE
HL2 Best Practices

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#34]
There's still some remaining recommendations for OpenXR performance I haven't gotten to for StereoKit. Don't need to get them all in for 0.1, just need to review and snag the low hanging fruit for now.

Recommendations are all here:
https://github.com/microsoft/OpenXR-SDK-VisualStudio#understand-openxr-samples-and-best-practices-for-hololens-2

- [x] Rendertarget color format
- [x] Texture array rendertarget
- [x] Unbound reference space
- [x] MRC alpha blend

**Comment by thetuvix** [comment]
Heads up that we just refined the recommendations there, including fixing up the recommended pixel format to be `DXGI_FORMAT_B8G8R8A8_UNORM_SRGB`, which is more optimal for performance on HoloLens 2 than linear formats. (avoids a copy)  Be sure you've got a gamma-correct render pipeline as you switch from linear to `_SRGB` here.

**Comment by maluoi** [comment]
Thanks for the heads up! :)

**Comment by maluoi** [comment]
Moving last remaining item, depth sharing, to v0.2:
https://github.com/maluoi/StereoKit/issues/38
