### ISSUE TITLE
Unicode in Window titles

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#346]
## Describe the feature
Would be neat to support Unicode in window titles, currently it does not! Will need to peek at each platform, and probably the marshaling from C# to C.

## An example use-case
Wouldn't it be cool to title your app 🧐 ?

**Comment by paulmelis** [comment]
I'm curious what the current unicode support is in other UI elements? I had the impression it wasn't fully supported, having recently found that a certain character was not rendered correctly in a button label.

**Comment by maluoi** [comment]
This is actually specifically for OS application windows, not UI inside of StereoKit!

If there's characters that aren't rendering in your UI, it's because the current font doesn't have a glyph for that character. StereoKit works directly with font files, and will only fall back on explicitly loaded fonts. I haven't quite figured out how to mimic the total Glyph fallback behavior the OS provides!

Just as an example: the default StereoKit Font on Windows is composed of three font files, Segoe UI, 1 of 4 different Japanese font files, and the MDL2 icon font, if present. This covers most major glyphs, but misses a few obscure symbols, as well as emoji.

**Comment by paulmelis** [comment]
> This is actually specifically for OS application windows, not UI inside of StereoKit!

Ouch, wrong interpretation on my side!
