### ISSUE TITLE
Providing Eye Gaze Sample Time

### ISSUE THREAD

**Issue by sandrist** [maluoi/StereoKit#356]
The [OpenXR spec](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#XR_EXT_eye_gaze_interaction) indicates that it is possible to query the actual sample time for a given eye gaze pose, which is useful for reasoning about high accuracy eye tracking, computing precise velocities over time, etc. It would be great if StereoKit could also provide that information.

I've implemented and locally tested one possible approach, which I was wondering if you might be willing to provide feedback on in a PR? I'm open to alternative approaches to surfacing this information, of course.

Basically, we just need a slightly modified version of `openxr_get_space()` to get the gaze space along with this extra timing information (it's specific to just gaze, and doesn't seem to be anything analogous for the head or hands).

```csharp
bool32_t openxr_get_gaze_space(pose_t* out_pose, XrTime &out_sample_time, XrTime time) {
	if (time == 0) time = xr_time;

	XrEyeGazeSampleTimeEXT gaze_sample_time = { XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT };
	XrSpaceLocation space_location = { XR_TYPE_SPACE_LOCATION, &gaze_sample_time };
	XrResult        res = xrLocateSpace(xr_gaze_space, xr_app_space, time, &space_location);
	if (XR_UNQUALIFIED_SUCCESS(res) && openxr_loc_valid(space_location)) {
		memcpy(&out_pose->position, &space_location.pose.position, sizeof(vec3));
		memcpy(&out_pose->orientation, &space_location.pose.orientation, sizeof(quat));
		out_sample_time = gaze_sample_time.time;
		return true;
	}
	return false;
}
```

Then this sample time can be accessible in `Input.cs` as something like `Input.EyesSampleTime`.

Thoughts?

**Comment by sandrist** [comment]
One immediate question is how to fill in that information when eye gaze is simulated in a "flatscreen" mode... Perhaps it should indicate the same as OpenXR.Time? Or just a default value (0)?

**Comment by maluoi** [comment]
Okay, this is certainly interesting! The general approach you've outlined here seems reasonable, but gets a bit sticky when referring to time.

StereoKit tracks its own idea of time that doesn't match up directly with OpenXR's, so surfacing an OpenXR time in the `Input` class seems like it would not be all that intuitive. `Input.EyesSampleTime` if implemented, should probably return a value converted to StereoKit time! I don't currently have a great mechanism for that, but it could be possible.

An alternative route to this could be to surface this data as `Backend.OpenXR.EyeSampleTime` instead. It's not particularly beautiful, and is a little distant from the Input class, but that would bypass the need to convert to StereoKit time?

**Comment by sandrist** [comment]
Makes sense! That would work totally fine for our purposes. We're already making use of the `Backend.OpenXR.Time` in other places, so it seems reasonable to similarly look for other OpenXR-related times in the same place. Shall I give that a shot and initiate a PR?

Out of curiosity, what's the main difference between "StereoKit time" and "OpenXR time"? Is it about the various Scale and Set operations available in the static `Time` class?

**Comment by maluoi** [comment]
Yeah, StereoKit time is somewhat mutable, and always starts with 0 when the application loads!

I'm not certain if `Scale` was a great idea, and I may yet deprecate it. But being able to explicitly set the time has been really valuable for debug and testing purposes.

If you make a PR for `Backend.OpenXR.EyeSampleTime`, I'll take it! :)

**Comment by maluoi** [comment]
I'll poke this thread when I ship a new preview build, will aim to do one this weekend :)

**Comment by sandrist** [comment]
Sounds good! No rush. Will that build include a Nuget release as well?

**Comment by maluoi** [comment]
Yep!

**Comment by maluoi** [comment]
v0.3.6-preview.5 is up now, and does contain this! :)

**Comment by sandrist** [comment]
Awesome, thanks!
