### ISSUE TITLE
StereoKit Visual Studio Template requires visual studio 2019

### ISSUE THREAD

**Issue by julenka** [maluoi/StereoKit#36]
Following getting started, I downloaded the vs template, but was unable to open it, with the error:

"This extension is not installable on any currently installed products."

I only had Visual Studio 2017 installed, but it turns out StereoKit needs Visual Studio 2019. It would be nice to mention this in the documentation.

**Comment by maluoi** [comment]
Getting started doc was more or less redone since this point! This detail was included :)
