### ISSUE TITLE
Use correct LUID when creating OpenXR session

### ISSUE THREAD

**Issue by gigadude** [maluoi/StereoKit#41]
I tried StereoKit with the Oculus runtime and ran into the issue at [openxr.cpp#L165](https://github.com/maluoi/StereoKit/blob/1b555a8a3908d16de6d76f447821b34f7d5338fe/StereoKitC/systems/platform/openxr.cpp#L165) because the laptop I was using has Optimus and creates an integrated rather than discrete graphics device.

**Comment by maluoi** [comment]
Aha! So that's what happens when you get a LUID wrong, that's actually pretty helpful, thanks :) I'll get on this.

I had heard Oculus might have a runtime up and working, but didn't realize it was accessible! Did you have to do anything tricky to enable that, or does it just go?

**Comment by gigadude** [comment]
@maluoi the runtime supports a preview OpenXR implementation but avoids installing the regkey for now, you can either point the `XR_RUNTIME_JSON` env var at the right oculus_openxr_*.json (32/64) or manually set the regkeys. The following script should do the trick for the latter:

```
@echo off
setlocal

set SCRIPTDIR=%~dp0

if "%1"=="/?" goto :usage

for /f "delims=" %%a in ('reg query "HKLM\SOFTWARE\Oculus VR, LLC" /v "Oculus" /reg:32 2^> nul') do set OculusDir=%%a
set OculusDir=%OculusDir:    Oculus    REG_SZ    =%
if "%OculusDir%"=="" goto :oculusnotfound

echo Setting %OculusDir% as the active OpenXR runtime...
reg add "HKLM\SOFTWARE\Khronos\OpenXR\1" /v "ActiveRuntime" /t REG_SZ /d "%OculusDir%\Support\oculus-runtime\oculus_openxr_64.json" /f /reg:64
reg add "HKLM\SOFTWARE\Khronos\OpenXR\1" /v "ActiveRuntime" /t REG_SZ /d "%OculusDir%\Support\oculus-runtime\oculus_openxr_32.json" /f /reg:32

:done
exit /b 0

:usage
echo Usage: "SetOculusOXR"
echo Sets Oculus as the default OpenXR runtime
exit /b 0

:oculusnotfound
echo "HKLM\SOFTWARE\Oculus VR, LLC\Oculus" not found, is the oculus runtime installed?
exit /b 0
```

**Comment by gigadude** [comment]
You might also want to change `Runtime.MixedReality` to `Runtime.OpenXR`  :wink:

**Comment by maluoi** [comment]
Thanks for the script! Should come in handy =D I wrote some code that may fix it, but I'm on my laptop right now. I'll verify/debug the rest of it later today when I get back to my desktop!

Regarding `MixedReality` vs. `OpenXR`: `Runtime.Flatscreen` encapsulates both Win32 and UWP already! I can also imagine a world in which I may end up implementing multiple MR APIs. Perhaps `Runtime` is the wrong name? Perhaps something like DisplayMode?

**Comment by maluoi** [comment]
Hey @gigadude! Try out the 0.1.3-rc4 NuGet package! I think that should fix it for you. But if it doesn't, let me know!

I'm more of a Vive person, so I'll need to swap out some hardware to get up and running to test with Oculus. But the code I changed will probably do it! :)

**Comment by gigadude** [comment]
Thanks I'll give it a try! For `Runtime` I think the distinction is emulation (flatscreen) vs. OpenXR, the whole point of OpenXR is that you shouldn't need to specialize for MR vs. Vive vs. Oculus any more.

**Comment by gigadude** [comment]
@maluoi I'm still hitting the same error, I think I've upgraded to 0.1.3-rc4 correctly:

```
PM> Install-Package StereoKit -Version 0.1.3-rc4
Restoring packages for c:\open\SKTest\SKTest.csproj...
  GET https://api.nuget.org/v3-flatcontainer/stereokit/index.json
  OK https://api.nuget.org/v3-flatcontainer/stereokit/index.json 479ms
  GET https://api.nuget.org/v3-flatcontainer/stereokit/0.1.3-rc4/stereokit.0.1.3-rc4.nupkg
  OK https://api.nuget.org/v3-flatcontainer/stereokit/0.1.3-rc4/stereokit.0.1.3-rc4.nupkg 334ms
Installing StereoKit 0.1.3-rc4.
Installing NuGet package StereoKit 0.1.3-rc4.
Committing restore...
Generating MSBuild file c:\open\SKTest\obj\SKTest.csproj.nuget.g.targets.
Writing assets file to disk. Path: c:\open\SKTest\obj\project.assets.json
Restore completed in 5.65 sec for c:\open\SKTest\SKTest.csproj.
Successfully uninstalled 'StereoKit 0.1.3' from SKTest
Successfully installed 'StereoKit 0.1.3-rc4' to SKTest
```

when I try to log the version with:
```
            Log.Info("StereoKit version: " + StereoKitApp.VersionName);
```
I get `C:\Program Files\dotnet\dotnet.exe (process 23376) exited with code -1073740940.`

**Comment by gigadude** [comment]
@maluoi I take it back, looks like we're getting further:
```
[SK info] Using graphics adapter NVIDIA GeForce RTX 2080 with Max-Q Design
[SK info] xrCreateSwapchain failed
```
For the OpenXR failures you should log the error-code as a string, there should be an _openxr_reflection.h_ header which makes that easy...

**Comment by maluoi** [comment]
Alright, progress indeed! I didn't realize openxr_reflection was around, that'll definitely be handy! Thanks for pointing that out :)

I'll set up my Oculus tonight and give that a whirl, I suspect I'll see that on my end too. Each platform seems to prefer a different swapchain format, it's possible I just don't have the Oculus one on my list!

**Comment by maluoi** [comment]
Alright, I found it. It looks like the Oculus OpenXR implementation doesn't support texture arrays quite yet! Texture arrays are used for single pass instanced rendering, and StereoKit only does single pass instanced right now. This is probably due to their implementation being unfinished =/

I'm going to think on this one a bit more and do some research. If we wait, it should just work as they light up features. But I'd really like StereoKit to work with Oculus sooner rather than later! I'll see if I can find a nice solution that'll work in the meantime.

**Comment by gigadude** [comment]
@maluoi good to know, texture array support should be in reasonably soon (I'm working on it, it's a complex change).

**Comment by maluoi** [comment]
Oh wow, alright! Good luck with implementing it :) I'll definitely be looking forward to that!

**Comment by maluoi** [comment]
@gigadude Do you by any chance know if the release that was just announced will include support for texture arrays? I'd love to have StereoKit up and running for that release, just need to know if I should have a workaround ready by then, or if I can rely on it to just work?

**Comment by gigadude** [comment]
I did manage to get texture array support working but unfortunately it
won't be out till v17, two releases from now.

  - Ed

**Comment by maluoi** [comment]
v17 is out now, and it looks like it works great! Awesome work, @gigadude thank you :) If I need to get assistance, or report bugs for OpenXR on Oculus, do you know of any spot I should gravitate towards?

I added Oculus bindings, and fixed some interaction profile code that unblocks the rest of this! ( da79cbfa2653c00f90e62b481424a06da3dc9ae3 ) Should work from /develop, or if using the template/NuGet, the v0.2-preview.2 package.

**Comment by gigadude** [comment]
Cool I'll give it a try
