### ISSUE TITLE
DLL not found exception when trying to build x64 for HoloLens 2 Emulator

### ISSUE THREAD

**Issue by ahorn42** [maluoi/StereoKit#43]
Hi and at first - thanks for the nice work!

I have a problem, when I try to run the example in the HoloLens 2 Emulator. As I unfortunately don't have a HL2 available yet I wanted to have look at you framework in the emulator.

If I am right the emulator for HL2 does not use ARM64 like the real device, but x64 or x86 to run the application. For that reason I choose the config `Debug, x64, StereoKitTest_UWP, HoloLens 2 Emulator`. But when starting this, I am getting an exception complaining about a missing DLL file `StereoKitC.dll`.
Building and running it as x64 for Local Machine works as expected. (Beside the fact I would expect to run the app in the Windows MR Portal, instead of a UWP Desktop application - but that's not related to my question here ;) )

![image](https://user-images.githubusercontent.com/5106205/72601609-02f69680-3916-11ea-85c1-44962121ab07.png)

Did I miss something or do I need to run some scripts first?

**Comment by maluoi** [comment]
I've had a bit of trouble with this particular scenario, but it shouldn't be present if you're using the NuGet package! Release mode should also work fine.

The UWP project has been pretty fiddly about referencing that native DLL, and while I've gotten most cases working, the emulator hasn't been on my hit-list! I'll see if I can figure it out, but given how slow and difficult to use it is, I rarely recommend anyone to use the Emulator for regular development! I use a WMR headset with a Leap Motion on it, but controllers work great too.
