### ISSUE TITLE
HL1 Compatability

### ISSUE THREAD

**Issue by techtide** [maluoi/StereoKit#44]
Hello,

This looks like a great project. I see that it currently is only compatible to build for ARM64, which is 64-bit and thus only works on the HL2. Is there planned availability for the 32-bit HL1?

Thanks in advance, and I look forward to hopefully being able to use StereoKit soon.

techtide

**Comment by maluoi** [comment]
StereoKit is based on OpenXR for MR platform compatibility, so it's dependent on that. I don't believe it's very likely, but if it ever gets added then I'll open this back up and make sure it works.
