### ISSUE TITLE
AccessViolation when attempting to set a texture to Default.Material.Copy()

### ISSUE THREAD

**Issue by craigomatic** [maluoi/StereoKit#45]
I noticed this in a project I'm working on; if I take a copy of the default material for a mesh, then attempt to set a texture to that material, it ends in an AccessViolationException. If I don't copy the material everything is fine, except all the models in my scene inherit that texture.

Here's some code that you can drop into your test project to repro:

```csharp
public class DemoTextureCrash : IDemo
{
    private Model _Model;

    public void Initialize()
    {
        _Model = Model.FromMesh(Mesh.GenerateCylinder(10, 1, Vec3.Up), Default.Material.Copy());            
    }

    public void Shutdown()
    {

    }

    private bool _DoOnce;

    public void Update()
    {
        if (!_DoOnce)
        {
            var mat = _Model.GetMaterial(0);
            mat.SetTexture("diffuse", Tex.FromFile("Floor.png"));

            _DoOnce = true;
        }

        _Model.Draw(Matrix.T(Vec3.Zero));
    }
}
```

The exception is on this line in render.cpp during a call to Step:

`d3d_context->VSSetShader(shader->vshader, nullptr, 0)`

**Comment by maluoi** [comment]
Alright! Thanks, I'll take a look at this :)

**Comment by maluoi** [comment]
Thanks for the repro, that was quite helpful! :) Fix is in `develop`, and I'll probably push a new NuGet build later this weekend.

GetMaterial creates a new Material class to wrap the native pointer, and removes a reference counter in its destructor. But the GetMaterial function wasn't properly adding a reference! This resulted in the Model referencing a totally destroyed Material instance.
