### ISSUE TITLE
ISpatialAudioClient for audio on WMR platforms

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#46]
ISpatialAudioClient is the recommended method for rendering audio on a HoloLens! It does spatial audio and mixing on the HPU, so is largely free to use as far as the app is concerned. Win-win all around.

Reference implementation is here:
https://github.com/microsoft/spatialaudio-unity/tree/develop/Source/Spatializer/HoloLens2

**Comment by MikeChemi** [comment]
I'd love to help out here :)
