### ISSUE TITLE
Support for different Material for each Hand

### ISSUE THREAD

**Issue by doublerebel** [maluoi/StereoKit#66]
Related to #7, it would be great to support setting a different Material for each Hand.  This is something I noticed when developing the two-handed support for the Paint Tutorial in maluoi/StereoKit-PaintTutorial#2 -- both hands must be the same color, since they use the same material.

Additionally, I can think of many situations where a material should be different for each hand, e.g. if the user is holding a tracked instrument or device in one hand, and using the other hand for gestures or hologram manipulation.

Thanks for StereoKit, it's been easy to get up and running and read the docs/source to find solutions!

**EDIT:**
Sources that would need refactor include:
https://github.com/maluoi/StereoKit/blob/3f83990ed6de0807735d8485664bf9350c37fc8a/StereoKit/Util/Defaults.cs#L35
https://github.com/maluoi/StereoKit/blob/3f83990ed6de0807735d8485664bf9350c37fc8a/StereoKit/Util/DefaultIds.cs#L24
https://github.com/maluoi/StereoKit/blob/3f83990ed6de0807735d8485664bf9350c37fc8a/StereoKitC/systems/hand/input_hand.cpp#L162-L219

**Comment by maluoi** [comment]
I haven't documented a lot of the Input class methods yet, I think there's still some things I've been waiting to settle on before I started writing that up in earnest. But there's a few functions there you'd be interested! Hand materials among them :)

Input.HandMaterial lets you set a different material for each hand! The idea is that you can clone the default hand material, and modify it as you see fit, and assign it to whichever hand you prefer. I didn't do this in the painting sample to keep things a little shorter and simpler, but it might still be something I revise later :)

**Comment by maluoi** [comment]
I've also got some demo code that shows how to adjust transparency and color along fingers as well by modifying the texture:
https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/Demos/DemoHands.cs#L118

**Comment by doublerebel** [comment]
Aha, I did not notice Input.HandMaterial, thanks!  I tried to get at it through Input.Hand(handed).Material, which is private so I thought there wasn't an API.  I will give that a shot.

**Comment by maluoi** [comment]
Added some additional docs for the Input class, they'll show up when v0.3 goes live!
