### ISSUE TITLE
Template updates

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#71]
Adjust the starting position of the default cube, so it's visible to AR/VR users right away on application start.

.Net Core Asset folder automatically copy files! Asset folder settings too.

Research a .Net Core + UWP unified project template.

**Comment by maluoi** [comment]
Mostly complete in: 3f83990ed6de0807735d8485664bf9350c37fc8a

Added better support for the Asset folders, these should now properly copy files to the output directory!

Also added some additional code to the default scene. This includes a floor grid visible only in VR using a custom shader, and a grabbable generated cube.

UWP doesn't play well with Oculus right now, need to check on that before I'll call this finished.

**Comment by Mukeshk1407** [comment]
.Net Core Stereo Kit Template project have a AR functionality ? 

I am using Oculus Quist 2 , How can I see my model in AR in that device?

**Comment by maluoi** [comment]
Quest 2 uses a nonstandard passthrough extension, here's an `IStepper` that will enable it on Quest!
https://github.com/StereoKit/StereoKit/blob/develop/Examples/StereoKitTest/Tools/PassthroughFBExt.cs

You can see an example of a project using this `IStepper` here:
https://github.com/maluoi/SKDesktopDuplicator

You may also want to try asking questions over in the Discussions tab next time :)
