### ISSUE TITLE
Multi-Platform shader build

### ISSUE THREAD

**Issue by maluoi** [maluoi/StereoKit#77]
Current shader system has the ability to store multiple shader blobs for different platforms already! Now we'll just need to hook in some cross-platform compilation for Android platform. This may mean run-time shader compile may not be possible on all platforms, so extra emphasis should be placed on external shader build tools.

**Comment by StephenHodgson** [comment]
Have you considered using https://github.com/bkaradzic/bgfx?

**Comment by maluoi** [comment]
I considered it, and decided against it! It has way too much code in it, and doesn't use a real shader language. I also considered sokol_gfx, and webgpu and may have looked at some other options too, but decided against those as well.

I'm currently working on https://github.com/maluoi/sk_gpu instead, which I managed to get supporting full HLSL, and comes as a single header file! It's still a bit progress, but currently does work on Quest as well as Windows. I'm working on integrating this into StereoKit right now!

**Comment by StephenHodgson** [comment]
Yes, I have been tracking your progress there with sk_gpu. Looks promising!

**Comment by maluoi** [comment]
[sk_gpu](https://github.com/maluoi/sk_gpu) now has multi-platform shader build abilities through [skshaderc](https://github.com/maluoi/sk_gpu/tree/master/skshaderc). It'll continue to evolve, but this functionality is usable in the sk_gpu branch in this repo!
