### ISSUE TITLE
CreateSwapchain failure with Oculus OpenXR Runtime (Quest/Link)

### ISSUE THREAD

**Issue by gsbain** [maluoi/StereoKit#82]
Symptoms are from a compile-run of the default app from a fresh NuGet install of StereoKit 0.2 in Visual Studio 2019.

Command window log is:
[SK info] xrCreateSwapchain failed [XR_ERROR_VALIDATION_FAILURE]
[SK error] Couldn't create OpenXR view swapchains!
[SK warning] Couldn't create StereoKit in MixedReality mode!
[SK info] Runtime falling back to Flatscreen

I presume the failure occurs at line 282 of "openxr_view.cpp"

In the headset, some things are initialized before the failure. Even after the failure, the controllers are tracked, hand avatars appear and respond to finger movements, a shaded floor and ceiling appear, and a curved panel appears with the text "Dotnet loading...".

A window does appear on the desktop monitor with the expected cube, and interactions using the desktop mouse work as expected.

Graphics card: Nvidia GTX1070, with current driver release and a fresh install of Oculus runtime.

**Comment by maluoi** [comment]
Thanks for reaching out! Could you tell me which version of Oculus you're using? This looks a lot like what you'd see in Oculus versions 16 and earlier. You may need to be on the beta channel to get access to 17, which introduced the necessary features for StereoKit to run!

If that's not it, could you set Log.Filter = LogLevel.Diagnostic, and see what else comes up?

**Comment by gsbain** [comment]
Your guess was correct. After install of Oculus PC Runtime v17 Beta, all is A-OK. Thanks!

The update process on the Oculus end was not exactly seamless and eventually required resets of both the WinPC and the Quest before things started working.

Should we close this issue or leave it up for a while to as a signpost for others?  Alternately, is there a FAQ or some other forum where such info should live?

BTW, Guy Godin has tweeted an aspiration to support OpenXR in (the sideloaded version of) Virtual Desktop.  Given his impressive productivity, perhaps there will be a useful tetherless option for StereoKit-PC/Quest fairly soon.

Are you interested in possible mission creep to include native StereoKit support for Oculus Mobile?

**Comment by maluoi** [comment]
Just added a note about v17 to the started guide, so we can close this here :) Shouldn't need it up for long, Oculus looks like they do updates on a monthly schedule!

I'm absolutely interested in supporting Quest as a standalone platform! And that's actually my primary focus for v0.3 :) I've been doing a bunch of code related to OpenGL/Vulkan to feel out exactly how I want to do it. Since that would be opening up platform support for Android, it's entriely possible for me to broaden the scope of that a bit to hit Linux, and longer term, possibly WASM/WebXR as well!

So v0.3 will definitely have Quest support! But it's definitely a pile of work!

**Comment by maluoi** [comment]
Also, if you have a suggestion for where content and tips should live, outside of the docs, I'd be super curious! Right now, StereoKit has a small channel on the HoloDeveloper's slack, but that's not exactly long-term persistent, or easily searchable. A forum sounds tempting, but is perhaps overkill? Github issues is actually decently searchable/discoverable, but is very specifically a assistance format. Not sure what other people are doing these days :)

**Comment by gsbain** [comment]
Impressive roadmap.
Have you considered bringing in a wgpu dependency as a render backend? Perhaps that could cover a bunch of issues at once - DX12, Vulkan, and Metal support, along with a partly-to-mostly paved path to future WGPU/WebXR support.

**Comment by maluoi** [comment]
I had actually been looking pretty hard at GLES lately. I thought WebGPU was a little too early to get onboard with, but you made me pretty curious! Aaaand it looks like it's a fair bit further along than I thought, including emscripten support!

I'll definitely be reconsidering that then :) Thanks for bringing that up!

**Comment by gsbain** [comment]
In my limited testing, wgpu seems almost ready for prime time. Also, Mozilla and Google are working toward common native C API's for wgpu and Google's Dawn:
https://dawn.googlesource.com/dawn

**Comment by maluoi** [comment]
Ok, Dawn looks pretty sweet at a casual glance! I will -definitely- be taking that for a spin!
