### ISSUE TITLE
Oculus OpenXR is enabled for all users by default now.

### ISSUE THREAD

**Issue by gigadude** [maluoi/StereoKit#89]
The Oculus v19 runtime will automatically point the ActiveRuntime registry key at our PC runtime for all users now, there should be no special setup required. Note if the regkey is already set we'll honor that and leave it pointing at whatever it was pointing at, so you'll have to manually change the regkey to switch runtimes (the OpenXR committee is planning on an automatic switching protocol at some future date).

**Comment by maluoi** [comment]
Oh very cool, thanks for letting me know! I'll update the docs to reflect this :)
