### ISSUE TITLE
Help request to access SpatialMapping data

### ISSUE THREAD

**Issue by halilibrahim** [maluoi/StereoKit#91]
Hi,
Thanks for great work on StereoKit.

I'm trying to find a way to access spatial mapping data (with hololens 2) on a StereoKit application. I've tried to access as shown in [HolographicSpatialMapping UWP sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/HolographicSpatialMapping). But got exception with message _"The application called an interface that was marshalled for a different thread"_ after calling [HolographicSpace.CreateForCoreWindow method](https://docs.microsoft.com/en-us/uwp/api/windows.graphics.holographic.holographicspace.createforcorewindow?view=winrt-19041).

Are there any methods to access HolographicSpace (and also SpatialCoordinateSystem, CurrentFrame etc...) which has already been created with OpenXR of StereoKitApp? 

(like in Unity Native.GetHolographicSpace)
https://github.com/needle-mirror/com.unity.xr.windowsmr/blob/05883fe781c9dd41fa09fd6a11e6d4a61dc0430b/Runtime/WindowsMREnvironment.cs#L17-L23

**Comment by maluoi** [comment]
Alright, I haven't used the spatial mapping APIs yet, so I'm probably on somewhat shaky ground here! I've briefly looked into it in the past, but didn't make it too far.

The core problem though, is there there are two separate APIs, OpenXR, and Windows Holographic (aka Mirage). The WMR implementation of OpenXR may or may not sit on top of Mirage. I believe it currently does? But there's no guarantee it will be that way in the future. So, doing interop between the two can be hack-ey, or even impossible.

The only big piece of interop code we really have access to here is the `XR_MSFT_spatial_graph_bridge` OpenXR extention. This is exposed in StereoKit through `Pose.FromSpatialNode`, and you can see it being used in the [docs for using the QR code library](https://stereokit.net/Pages/Guides/Using-QR-Codes.html). Works great there, but if the spatial mapping API doesn't provide a similar Spatial Node, you may be out of luck for the immediate future.

However! There is some good news. Scene understanding is coming to OpenXR, and there is already a `XR_MSFT_scene_understanding_preview` extension available if you're using a preview runtime. There's a few details about preview features [here](https://github.com/microsoft/OpenXR-MixedReality#openxr-preview-extensions). I **don't** have this implemented in StereoKit yet though, as I'm currently towards the end of a _very_ big update for Quest/Android support. It is very high on my list though, so I'll be digging into that pretty soon after I finish the Android update!

**Comment by maluoi** [comment]
Spatial mapping is now do-able in v0.3! This isn't through the upcoming scene_understanding extension, but through some interop extensions instead. This theoretically has a faster refresh rate than scene understanding will have, so this would probably still be the recommended approach for things like occlusion.

See this code for the SpatialSurfaceObserver -> StereoKit implementation:
https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/Tools/OcclusionMesh.cs

And then this code for how to use it:
https://github.com/maluoi/StereoKit/blob/master/Examples/StereoKitTest/Demos/DemoWorldMesh.cs
