### ISSUE TITLE
SDK Style csprojs

### ISSUE THREAD

**Issue by vpenades** [maluoi/StereoKit#96]
I've been trying to follow the project's architecture, and it's a bit hard given the project's csproj files have been written in the old style.

It would make goot to the project to convert them to 2019 SDK csprojs.

Also, it could be great to have an example using the nuget package instead of referencing the project directly. I picked the StereoKitTest example, and it boils down to this csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>    
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <AssemblyTitle>StereoKitCSTest</AssemblyTitle>
    <LangVersion>7.3</LangVersion>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>    

  <ItemGroup>
    <PackageReference Include="StereoKit" Version="0.2.2-preview.3" />
  </ItemGroup>  
  
</Project>
```

**Comment by maluoi** [comment]
They're probably due for an update, yeah. By any chance, do you know if this can be done for UWP projects, or just the .Net Framework ones?

Also, I wouldn't really recommend peeking at the csprojs for the test projects as reference. I do the references a differently so I can dev on them a little easier! Check out some of the [sample projects instead](https://stereokit.net/Pages/Guides/Learning-Resources.html), which do use NuGet for consuming StereoKit.

**Comment by capnmidnight** [comment]
It should be possible to create SDK Style projects targeting UAP10 using the MSBuildSdkExtras project: https://github.com/novotnyllc/MSBuildSdkExtras

**Comment by maluoi** [comment]
The [.Net Framework test project](https://github.com/maluoi/StereoKit/blob/develop/Examples/StereoKitTest/StereoKitTest.csproj) is now SDK style over on /develop.

I don't want to pull in any extra dependencies just for this, so I'm going to skip doing the same for the UWP project. Might revisit this idea someday in the future :)
